version: '3'
 
services:
  web:
    build: 
      context: ./ 
      dockerfile: Dockerfile-django
    image: pharma:v1
    container_name: site_pharmacie
    ports:
      - "8001:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - postgres_data:/app  # Assurez-vous que le chemin correspond à votre application Django
    networks:
      - mynetwork
    env_file:
      - .env
    # Utilisez le nom du réseau personnalisé ici

  db:
    image: postgres:latest
    container_name: bdpharmacie
    environment:
      POSTGRES_DB: formul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - mynetwork
     # Utilisez le nom du réseau personnalisé ici
  
  nginx:
    image: 'nginx:1.24-alpine'
    container_name: sitenginxP
    volumes:
      - ./formulaire:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - '8002:80'
    networks:
      - mynetwork


volumes:
  postgres_data:
  

networks:
  mynetwork:
    external: false  # Vous pouvez laisser cette partie inchangée

